### PR TITLE
Update code to comply with WP Coding Standards

### LINKED ISSUE #8: Set up project in Composer

### LINKED ISSUE #10: Ensure that code is compliant with WP Coding Standards

### LINKED ISSUE #11: Add PHP_CodeSniffer pre-commit hook

### PR DESCRIPTION
**Pull request by Rumperuu**
Updates the codebase to ensure compliance with the [WP Coding Standards](https://codex.wordpress.org/WordPress_Coding_Standards).

Also composerises the project to allow for the installation of a pre-commit PHP_CodeSniffer hook (and other hooks later on).

Close #8 
Close #10 
Close #11

### CODE REVIEW

**Comment by Rumperuu** [comment]
PHPCS is finally reporting 0 errors and 0 warnings. Just need to test to make sure everything's still working and then we should be good to go.

**Review by markcheret — APPROVED** [review]
Fantastic work

**Comment by markcheret** [comment]
No idea how to resolve the conflicts from my mobile phone app

**Comment by Rumperuu** [comment]
Going to leave this on draft until I've had a chance to test that everything is still working as before (I had to do a lot of RegEx wizardry)

**Comment by pewgeuges** [comment]
Hi,

As reported in an urgent thread, it’s now broken, sorry.

Sure you will get it to work again, but honestly I don’t see the point in
doing all this WP compliance stuff.

They don’t give us anything for it, and I even suspect they think much good.

There is zero benefit for our users, while developers are impacted by the
unwieldy variable names. Moreover, snakecase is harder to type on a QWERTY,
as you need to not only press shift, but reach out to the minus key instead
of keeping type the name. The underscores are designed for Hungarian to
stay readable, while the name should be one piece.

Should I spend  all the time now commenting on GitHub, or is it fine by
email?

Sorry for duplicate addressees.

Cheers,
Marcel

**Comment by Rumperuu** [comment]
Closed in favour of rebase #32

**Pull request closed without merging**
