### PR TITLE
ci: improve linting

### PR DESCRIPTION
**Pull request by Rumperuu**
Adds HTML linting for templates, YAML validation for GitHub Actions workflows, updates the JS WPCS linter standard used, moves as many config files into `package.json` as possible and tweaks some of the GitHub Actions workflows

### CODE REVIEW

**Comment by Rumperuu** [comment]
@markcheret Any idea why the `OSSAR-Scan` and `build` Actions are stalled? They've been pending since I made this PR last night, but there's no YAML files for them in `.github/workflows/`.

**Comment by markcheret** [comment]
> @markcheret Any idea why the `OSSAR-Scan` and `build` Actions are stalled? They've been pending since I made this PR last night, but there's no YAML files for them in `.github/workflows/`.

Those checks were previously named differently. I made their passing a requirement for a PR to be merged. All updated now, to reflect the new situation.

**Review by markcheret — APPROVED** [review]
Thanks. Makes sense to restructure it.

**Comment by markcheret** [comment]
@Rumperuu since this changes the organisation of checks, this PR needs to be merged soon, before the others will pass their checks :)

**Review by lolzim — APPROVED** [review]
OK, nice work! I didn't knew there was a wp_json_encode() ! 
I should look at those more often.

**Pull request merged**
