### PR TITLE
Update code to comply with WP Coding Standards (*fourth* time's the charm!)

### LINKED ISSUE #8: Set up project in Composer

### LINKED ISSUE #10: Ensure that code is compliant with WP Coding Standards

### LINKED ISSUE #11: Add PHP_CodeSniffer pre-commit hook

### LINKED ISSUE #46: Dashboard reports incorrect Plugin version number
**Describe the bug**
The 2.5.6 codebase was migrated, but in the WordPress dashboard it incorrectly reports the Plugin version as 2.5.6d4.

### PR DESCRIPTION
**Pull request by Rumperuu**
### Description of Changes

Updates the codebase to ensure compliance with the [WP Coding Standard](https://duckduckgo.com/?t=canonical&q=wp+coding+standard&ia=web).

Also Composerises the project to allow for the installation of a pre-commit PHP_CodeSniffer hook (as well as other hooks later on).

### History

This is a copy of #38 after it was un-merged in #49.

### Additional Notes

This branch's commit history will be squashed on merge, so do not make any commits to this branch that you're going to want to remain in the project history. Keep it scoped to WP Coding Standards compliance _only_.

### Actions

Replace #38

Close #8
Close #10
Close #11
Close #46

### CODE REVIEW

**Comment by Rumperuu** [comment]
@pewgeuges CSS issue should be fixed in https://github.com/markcheret/footnotes/pull/50/commits/600910d9eef5627127e4240b03b462614341bcd9 — if there's anywhere else where output escape functions are breaking things (although I can't think of where they might be now the CSS is done) then just replace them with PHPCS disable comments for now.

**Comment by pewgeuges** [comment]
> @pewgeuges CSS issue should be fixed in [600910d](https://github.com/markcheret/footnotes/commit/600910d9eef5627127e4240b03b462614341bcd9) — if there's anywhere else where output escape functions are breaking things (although I can't think of where they might be now the CSS is done) then just replace them with PHPCS disable comments for now.

AFAICS, you fixed the header output, where minified or halfways minified CSS makes actually some sense except for support, which shouldn’t be a reason to not minify given we can reformat it if needed.

The bug I referred to was happening in the dashboard, where Custom CSS is minified with spaces on save, something inacceptable for users.

Moreover, HTML tags are deleted (stripped off) from the labels, where users may add them. E.g. https://wordpress.org/support/topic/how-do-i-eliminate-the-horizontal-line-beneath-the-reference-container-heading/ shows how a user added markup to the label, for a suboptimal result that was subsequently fixed and triggererd the addition of  2 new settings, one of which to select the element natively. But stripping off these tags is inacceptable for users. Also witnessed in referrers (string before/after). Escaping all this is detrimental and it’s also pointless, as it is not clear to what avail this overkill security scheme is enforced in the dashboard of a plugin in an environment where other plugins can help add heaps of internal scripts. No need to hijack any Footnotes setting to do that.

The real use of escapement is to address security issues about visitor input, where everyone out there can try to inject malicious code. That however is not a concern in the Footnotes plugin.

On top of all that, even the optional Footnotes ad string (e.g. I love Footnotes) to be displayed in the footer of the public pages is now escaped.

If a validation tool complains about non-escaped output without considering where it originates from, then that tool is either misconfigured, or it’s incompetent.

I can’t seem to understand why we should turn the validator off at every non-escaped output variable instead of editing the tools’ global settings for this codebase.

**Review by pewgeuges — CHANGES_REQUESTED** [review]
This branch has issues that make it a threat to the plugin’s stability and usability. It disrupts the plugin’s dashboard UX and capabilities, see https://github.com/markcheret/footnotes/pull/50#issuecomment-786992125

Also, this branch goes beyond its scope by making these disruptive changes to the code.

Can the excess be safely reverted, or would it be more efficient to restart from zero (2.5.6, or better, now 2.5.7, or oncoming 2.6.0 if AMP compat can be provided and released within a useful delay)?

I think best would be to clearly design the scope and the steps, e.g.:
1. Fix spacing issues;
2. Convert CamelCase to snake_case in PHP while sparing JS native methods;
3. Change class names in accordance with file names, as files mustn’t be renamed at this point;
4. Change wrong BOOL type to STR in Hungarian constant names;
5. Convert outcommented code to docblocks when it’s interspersed with data needed to finish the docblock attributions and documentation;
6. Add @‌todo docblocks without content wherever docblocks are missing, if needed to pass validation.

I would try to redo it based on your instructions while refraining from altering the code further, for the sake of a clean branch that can be safely merged without fear of compromising the plugin and requiring a long testing cycle just for the merger of this coding standards conformance branch.

Sadly that would invalidate much of your hard work. But Footnotes’ users are top priority and must not become the victims of project-internal issues.

**Comment by Rumperuu** [comment]
> AFAICS, you fixed the header output, where minified or halfways minified CSS makes actually some sense except for support, which shouldn’t be a reason to not minify given we can reformat it if needed.
> The bug I referred to was happening in the dashboard, where Custom CSS is minified with spaces on save, something inacceptable for users.

My mistake, I misunderstood where you were having the issue.

> Moreover, HTML tags are deleted (stripped off) from the labels, where users may add them. E.g. https://wordpress.org/support/topic/how-do-i-eliminate-the-horizontal-line-beneath-the-reference-container-heading/ shows how a user added markup to the label, for a suboptimal result that was subsequently fixed and triggererd the addition of 2 new settings, one of which to select the element natively. But stripping off these tags is inacceptable for users. Also witnessed in referrers (string before/after). Escaping all this is detrimental and it’s also pointless, as it is not clear to what avail this overkill security scheme is enforced in the dashboard of a plugin in an environment where other plugins can help add heaps of internal scripts. No need to hijack any Footnotes setting to do that.
> 
> The real use of escapement is to address security issues about visitor input, where everyone out there can try to inject malicious code. That however is not a concern in the Footnotes plugin.
> 
> On top of all that, even the optional Footnotes ad string (e.g. I love Footnotes) to be displayed in the footer of the public pages is now escaped.

Agreed, the use of output escaping is not necessary within the context of this Plugin. For now, I've removed all of the output escape and input sanitisation functions in 25c3f2f and replaced them with file-level PHPCS suppressions for those rules. I'll have a proper look into whether the same is true of input sanitisation (i.e., for `$_REQUEST` and `$_POST` values) when I get around to tackling #52.

> I can’t seem to understand why we should turn the validator off at every non-escaped output variable instead of editing the tools’ global settings for this codebase.

The use of file-level suppression comments solves this.

> This branch has issues that make it a threat to the plugin’s stability and usability. It disrupts the plugin’s dashboard UX and capabilities, see [#50 (comment)](https://github.com/markcheret/footnotes/pull/50#issuecomment-786992125)

Fixed in 25c3f2f

> Also, this branch goes beyond its scope by making these disruptive changes to the code.

Incorrect. The scope of this PR is to add pre-commit linting to enforce compliance with the WP Coding Standards. The linter raises errors for unescaped output, and so solving that issue (whether by escaping output or suppressing the error) is within this scope.

> Can the excess be safely reverted, or would it be more efficient to restart from zero (2.5.6, or better, now 2.5.7, or oncoming 2.6.0 if AMP compat can be provided and released within a useful delay)?

As @markcheret has said elsewhere, the current priority is getting the codebase up-to-snuff (provided there are no critical/security fixes to implement).

> I think best would be to clearly design the scope and the steps, e.g.:

As stated above, the scope of this branch is clear: implement pre-commit PHPCS validation to enforce compliance with the WP Coding Standards, and ensure that all code passes. This necessarily involves a huge number of minor changes (e.g., double quotes to single quotes), but it also requires a few manual changes (e.g., the output escaping). These manual changes are where issues may arise, but they make up a minority of the overall changeset.

> Sadly that would invalidate much of your hard work. But Footnotes’ users are top priority and must not become the victims of project-internal issues.

Again as per @markcheret—excluding any critical/security issues that may arise—merging this PR is currently the priority. Once we've done so, we can return to regular bugfixing and adding features. As the standardisation of the codebase will not merit a new version of the Plugin, we can still have plenty of time to catch any other issues that may arise (though between your thorough code review and the reversion of output escaping in 25c3f2f (which was one of the most impactful changes made originally) I think that is unlikely).

**Comment by pewgeuges** [comment]
> > AFAICS, you fixed the header output, where minified or halfways minified CSS makes actually some sense except for support, which shouldn’t be a reason to not minify given we can reformat it if needed.
> > The bug I referred to was happening in the dashboard, where Custom CSS is minified with spaces on save, something inacceptable for users.
> 
> My mistake, I misunderstood where you were having the issue.

No problem.

> > Moreover, HTML tags are deleted (stripped off) from the labels, […]
> 
> Agreed, the use of output escaping is not necessary within the context of this Plugin. For now, I've removed all of the output escape and input sanitisation functions in [25c3f2f](https://github.com/markcheret/footnotes/commit/25c3f2f12eb5de1079e9215bf624ec4289b095a5) (you can check by running `grep -r 'esc_\|wp_kses_\|sanitize_\|wp_filter_' . --exclude-dir={.git/,.phpdoc/,vendor/,docs/,languages/}`) and replaced them with file-level PHPCS suppressions for those rules.

Thank you for fixing the escapement problem.

> I'll have a proper look into whether the same is true of input sanitisation (i.e., for `$_REQUEST` and `$_POST` values) when I get around to tackling #52, but for now the errors are suppressed so that's considered fixed within the scope of this PR.

`$_POST` is used for the dashboard, so you won’t need to change anything, because the input is expected to stay unaltered as it is.

> > I can’t seem to understand why we should turn the validator off at every non-escaped output variable instead of editing the tools’ global settings for this codebase.
> 
> The use of file-level suppression comments solves this.

 File level configuration seems a good compromise between project-wide and local.

> > This branch has issues that make it a threat to the plugin’s stability and usability. It disrupts the plugin’s dashboard UX and capabilities, see [#50 (comment)](https://github.com/markcheret/footnotes/pull/50#issuecomment-786992125)
> 
> Fixed in [25c3f2f](https://github.com/markcheret/footnotes/commit/25c3f2f12eb5de1079e9215bf624ec4289b095a5)

Thanks!

> > Also, this branch goes beyond its scope by making these disruptive changes to the code.
> 
> Incorrect. The scope of this PR is to add pre-commit linting to enforce compliance with the WP Coding Standards. The linter raises errors for unescaped output, and so solving that issue (whether by escaping output or suppressing the error) is within this scope.

[WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) does not seem to recommend Lint. The compiler catches bugs, while a linter seems to enforce general or common-sense rules that may, as you state, not apply to a given codebase.

> > Can the excess be safely reverted, or would it be more efficient to restart from zero (2.5.6, or better, now 2.5.7, or oncoming 2.6.0 if AMP compat can be provided and released within a useful delay)?
> 
> As @markcheret has said elsewhere, the current priority is getting the codebase up-to-snuff (provided there are no critical/security fixes to implement).

I tried to carefully evaluate @markcheret’s directives and didn’t suspect that I got him wrong, as he both mentioned “compliance” AND “Let's also continue what has been going on bugfixes and enhancements can be done alongside if the codebase permits.” The “alongside” is what allowed to release bugfix 2.5.7 in real time, which is also what I anticipated the possible need of.
> 
> > I think best would be to clearly design the scope and the steps, e.g.:
> 
> As stated above, the scope of this branch is clear: implement pre-commit PHPCS validation to enforce compliance with the WP Coding Standards, and ensure that all code passes. This necessarily involves a huge number of minor changes (e.g., double quotes to single quotes),

I’m fine with that, no problem for me. It’s even easier to type,

> but it also requires a few manual changes that are more impactful and have the potential to introduce problems (e.g., the output escaping).

I’m sorry that the linter or whatever tool got you to go to that trouble.

> These manual changes are where issues may arise, but they make up a minority of the overall changeset.

I’m glad if that’s all.

> > Sadly that would invalidate much of your hard work. But Footnotes’ users are top priority and must not become the victims of project-internal issues.
> 
> Again as per @markcheret—excluding any critical/security issues that may arise—merging this PR is currently the priority. Once we've done so, we can return to regular bugfixing and adding features on the standardised codebase (rather than maintaining two variants—it required a non-trivial amount of effort to backport the 2.5.7 bugfix in #51

Thank you very much for integrating the 2.5.7 changes!

> and that only altered 4 or 5 lines).

Indeed 2.5.7 was basically 1 line of code and 1 new docblock above it.

> As the standardisation of the codebase will not merit a new version of the Plugin, we will still have plenty of time still to catch any other issues that may slip through during subsequent normal development, though between your thorough code review and the reversion of output escaping in [25c3f2f](https://github.com/markcheret/footnotes/commit/25c3f2f12eb5de1079e9215bf624ec4289b095a5) (which was one of the most widespread impactful manual changes made) I think that is unlikely.

Seems unlikely, I thinks so too. Will just review the code again, hoping to catch any remainder.

> In a worst-case scenario, even if something really obscure breaks and we don't notice until we get a bug report in five months time, then that's something we can fix then and there easily enough. Only 50% of users are on the latest version, after all.

Sigh.

**Review by pewgeuges — APPROVED** [review]
I’m unable to review the codebase again, and it’s superfluous since @Rumperuu assessed all problems as solved.

Moreover the plugin escapes quotation marks in user input! It’s unusable for custom CSS involving HTML argument values. The plugin is still so buggy it would be shameless to submit it to AMP-WP as-is even after adding AMP compat.

RTL compat bugfix v2.5.8 needs to be fast-tracked instead, see [the latest support issue](https://wordpress.org/support/topic/right-to-left-text-problem/).

**Comment by markcheret** [comment]
@pewgeuges @Rumperuu is the escaping of quotation marks in the user input a new behaviour introduced by the refactoring here or has it historically been implemented?

**Comment by Rumperuu** [comment]
> RTL compat bugfix v2.5.8 needs to be fast-tracked instead, see [the latest support issue](https://wordpress.org/support/topic/right-to-left-text-problem/).

That's fine, 2.5.8 won't be a problem to backport.

> @pewgeuges @Rumperuu is the escaping of quotation marks in the user input a new behaviour introduced by the refactoring here or has it historically been implemented?

Investigating...

**Comment by pewgeuges** [comment]
> > RTL compat bugfix v2.5.8 needs to be fast-tracked instead, see [the latest support issue](https://wordpress.org/support/topic/right-to-left-text-problem/).
> 
> That's fine, 2.5.8 shouldn't be any bother to backport.

I did backport it, even prior to releasing it, but the line end issue has come back. Why is this branch using other line ends, and what can I do to address the problem?

Given this branch does not edit the style sheets, I pasted the modified ones over the existing ones. E.g. 12 minified style sheets were changed.

As of the readme.txt, I synced it alongside so it was handled the same way. Only footnotes.php was edited in the Git branch.

Now all these files are jumbled again.

Note that SVN does not have this issue.

> > @pewgeuges @Rumperuu is the escaping of quotation marks in the user input a new behaviour introduced by the refactoring here or has it historically been implemented?

It is a longlasting bug that I noticed only now. My bugreport is based on the plugin as it is deployed.

> I'm not able to reproduce this on either `main` or `wp-coding-standard--fresh`.

Congratulations: You already fixed it, then! But how on `main`?

> See [here](https://imgur.com/ojABXcA) for my custom CSS (with quotation marks) and [here](https://imgur.com/y7LL1Z2) the output. @pewgeuges have you definitely `pull`ed the branch since [25c3f2f](https://github.com/markcheret/footnotes/commit/25c3f2f12eb5de1079e9215bf624ec4289b095a5)?

Yes I do always pull, but for the releases I needed to revert to the current plugin, and develop and test therein, until this branch has been merged. Then you will commit it to SVN updating trunk/, and then we’ll be able to use and release it with the next due release, as you planned, should any urgency arise before setting up the workflow in GitHub is completed.

> Update: HTML elements within CSS are escaped; see [here](https://imgur.com/C216di4) for custom CSS and [here](https://imgur.com/kOKumiC) for output. This is also the case on `main`. I'm not sure if this is what @pewgeuges was referring to, however if it is then this is expected behaviour per the [CSS spec](https://drafts.csswg.org/css2/#propdef-content).

Thank you for all the tests. That is not what I’m referring to, but `html[dir="rtl"]` becomes `html[dir=\"rtl\"]` in the dashboard and the header. It’s a matter of escaping quotes WRT MySQL; the bug is to not revert the escapement. It happens in all input fields, such as the reference container label.

**Comment by Rumperuu** [comment]
> > > RTL compat bugfix v2.5.8 needs to be fast-tracked instead, see [the latest support issue](https://wordpress.org/support/topic/right-to-left-text-problem/).
> > 
> > 
> > That's fine, 2.5.8 shouldn't be any bother to backport.
> 
> I did backport it, even prior to releasing it, but the line end issue has come back. Why is this branch using other line ends, and what can I do to address the problem?
> 
> Given this branch does not edit the style sheets, I pasted the modified ones over the existing ones. E.g. 12 minified style sheets were changed.
> 
> As of the readme.txt, I synced it alongside so it was handled the same way. Only footnotes.php was edited in the Git branch.
> 
> Now all these files are jumbled again.
> 
> Thank you @Rumperuu for renormalising the line ends [f129f3a](https://github.com/markcheret/footnotes/commit/f129f3a39212419ec77a1b4d93aa5f7bd8bb21b1)

Not to worry, however it happened f129f3a has fixed the ‘Files Changed’ tab view so we're good to go!
 
> > > @pewgeuges @Rumperuu is the escaping of quotation marks in the user input a new behaviour introduced by the refactoring here or has it historically been implemented?
> 
> It is a longlasting bug that I noticed only now. My bugreport is based on the plugin as it is deployed.
> 
> > I'm not able to reproduce this on either `main` or `wp-coding-standard--fresh`.
> 
> Congratulations: You already fixed it, then! But how on `main`?

How strange, I'm getting the bug on `main` now — not sure why I wasn't before. However, it does appear to be fixed on `wp-coding-standard--fresh`. I'll be quite honest, I haven't got a clue what fixed it, but it's always nice when you accidentally manage to fix something that you didn't even know was broken!

Anyway, if there are no more issues identified with this branch by 20:00 UK time I will merge it into `main` and then we can crack on with normal development again!

**Comment by pewgeuges** [comment]
> > Thank you @Rumperuu for renormalising the line ends [f129f3a](https://github.com/markcheret/footnotes/commit/f129f3a39212419ec77a1b4d93aa5f7bd8bb21b1)
> 
> Not to worry, however it happened [f129f3a](https://github.com/markcheret/footnotes/commit/f129f3a39212419ec77a1b4d93aa5f7bd8bb21b1) has fixed the ‘Files Changed’ tab view so we're good to go!

If Footnotes’ GitHub main branch is now having other line ends than its SVN repo, should this be updated WRT line ends so that the issue won’t be replicated there?

> Anyway, if there are no more issues identified with this branch by 20:00 UK time I will merge it into `main` and then we can crack on with normal development again!

Will you commit the updated main branch again, for the changes to be visible on SVN?  (WordPress don’t require to only commit release versions.)

**Comment by Rumperuu** [comment]
> > > Thank you @Rumperuu for renormalising the line ends [f129f3a](https://github.com/markcheret/footnotes/commit/f129f3a39212419ec77a1b4d93aa5f7bd8bb21b1)
> > 
> > 
> > Not to worry, however it happened [f129f3a](https://github.com/markcheret/footnotes/commit/f129f3a39212419ec77a1b4d93aa5f7bd8bb21b1) has fixed the ‘Files Changed’ tab view so we're good to go!
> 
> If Footnotes’ GitHub main branch is now having other line ends than its SVN repo, should this be updated WRT line ends so that the issue won’t be replicated there?

I've not touched the SVN repo. since I cloned it to here, so the SVN codebase will have never received 8d0ebdb.

> > Anyway, if there are no more issues identified with this branch by 20:00 UK time I will merge it into `main` and then we can crack on with normal development again!
> 
> Will you commit the updated main branch again, for the changes to be visible on SVN?  (WordPress don’t require to only commit release versions.)

So once this PR is merged, we'll effectively have two codebases: _footnotes_ here in `main`; and _'footnotes_ over on the SVN `trunk`. _footnotes_ and _'footnotes_ will be feature-identical (as we've been backporting all changes from the SVN to here), and _footnotes_ will be fully-standardised.

You have more experience with the SVN than I do, but am I correct in thinking that once the merge here is complete, we'll be able to just copy the files in `main` (excluding the dev files like `.gitignore`, etc.) onto `trunk` and overwrite everything, so that both the Git and SVN repos contain the _footnotes_ codebase? And then when we've got a new feature/bugfix ready to release on here, we can copy the files over again and make a release so that 2.5.9 (or whatever its called) wraps up the standardisation changes too?

**Comment by pewgeuges** [comment]
> > If Footnotes’ GitHub main branch is now having other line ends than its SVN repo, should this be updated WRT line ends so that the issue won’t be replicated there?
> 
> I've not touched the SVN repo. since I cloned it to here, so the SVN codebase will have never received [8d0ebdb](https://github.com/markcheret/footnotes/commit/8d0ebdb8595ab698c50996bc268bcabae928294d).

That’s where I see the issue. You hinted that the original codebase is having CRLF, which is non-standard.

To prevent one instance of SVN diffs to be as unusable as what we were seeing here on GitHub at some point, the SVN codebase must receive one commit solely dedicated to EOL conversion, exclusively.

@Rumperuu: Would you like to checkout Footnotes on SVN again, apply EOL standardisation, and commit that change?

The expected outcome is that once you have merged `wp-coding-standard--fresh` into `main`, you will be able to commit Footnotes’ new codebase to SVN in order to have one SVN changeset entirely dedicated to WP Coding Standars compliance?

For sure, the changes proper to Footnotes’ next bugfixes and features must not be dissolved in, mixed up with, and hidden amongst the overwhelming changes made for the sake of standards conformance.

> > Will you commit the updated main branch again, for the changes to be visible on SVN?  (WordPress don’t require to only commit release versions.)
> 
> So once this PR is merged, we'll effectively have two codebases: _footnotes_ here in `main`; and _'footnotes_ over on the SVN `trunk`. _footnotes_ and _'footnotes_ will be feature-identical (as we've been backporting all changes from the SVN to here), and _footnotes_ will be fully-standardised.
> 
> You have more experience with the SVN than I do, but am I correct in thinking that once the merge here is complete, we'll be able to just copy the files in `main` (excluding the development-only files like `.gitignore`, etc.) onto `trunk` and overwrite everything, so that both the Git and SVN repos contain the _footnotes_ codebase?

Yes I think so too. But not before you committed the EOL conversion, so that the abovementioned commit will enable SVN to generate a meaningful changeset.

> And then when we've got a new feature/bugfix ready to release on here, we can copy the files over again and make a release so that 2.5.9 (or whatever it might be called) publishes the standardisation changes too?

That will be so nice and visible (already due to the many new files included in the download) that the changelog should probably have an entry for it?

> In which case (for my own benefit when I come to #30), the steps for an automated release workflow would be:

> 1. run a `build` command on this Git repo that excludes development-only files, minifies files,

Minification is not so easy. jQuery Tools is already minified, while most of the style sheets need concatenation prior to minification. That’s done semi-automatically using development/csscat.sh.

> updates the version number in `readme.txt`, etc.
> 2. take the resulting files and copy them to the SVN `trunk`, overwriting whatever's there
> 3. create a new `tag` on the SVN repo. from `trunk` with the new version number (`svn cp trunk tags/<version number>`)
> 
> Does that sound about right?

I’m wary of this way of automating things. Perhaps it can mitigate the risks involved by the new complexity.

**Comment by pewgeuges** [comment]
> > If Footnotes’ GitHub main branch is now having other line ends than its SVN repo, should this be updated WRT line ends so that the issue won’t be replicated there?
> 
> I've not touched the SVN repo. since I cloned it to here, so the SVN codebase will have never received [8d0ebdb](https://github.com/markcheret/footnotes/commit/8d0ebdb8595ab698c50996bc268bcabae928294d).

If we can be sure that SVN is EOL agnostic, it may not need it. But given GitHub is not, I doubt SVN is.

You are welcome to commit the EOL normalization and the standardised codebase. Hopefully SVN will then display a proper changeset, which I doubt it would without prior EOL normalisation.

> 
> > > Anyway, if there are no more issues identified with this branch by 20:00 UK time I will merge it into `main` and then we can crack on with normal development again!

Thank you for taking this step after you assessed all issues as solved!

> You have more experience with the SVN than I do, but am I correct in thinking that once the merge here is complete, we'll be able to just copy the files in `main` (excluding the development-only files like `.gitignore`, etc.) onto `trunk` and overwrite everything,

I see a problem in doing so without previously normalising the EOL in SVN. Yesterday I tried to get hold of a method to normalize EOL but failed. You do have this method. Would you like to do the EOL fix? (And update trunk/ with main/?)

> so that both the Git and SVN repos contain the _footnotes_ codebase?

I think that will be great!

> And then when we've got a new feature/bugfix ready to release on here, we can copy the files over again and make a release so that 2.5.9 (or whatever it might be called) publishes the standardisation changes too?

I would say yes, please go ahead.

> In which case (for my own benefit when I come to #30), the steps for an automated release workflow would be:
> 
> 1. run a `build` command on this Git repo that excludes development-only files,

For use in my local sandbox I’m currently deleting these files and folders:

```sh
#!/bin/bash
# 2021-02-28T2217+0100
# gwp.sh
rm -rf GW/.git
rm -rf GW/.github
rm -rf GW/docs
rm -rf GW/_tools
rm -rf GW/.gitignore
```

Is that correct? The docs are twice as heavy as the whole codebase (1.6MB adding to 0.8MB), and as already reported they’re of limited use.

> minifies files,

I think that this step may create more problems than it solves. The only file is settings.css, while all other stylesheets need to be concatenated first, as specified in development/csscat.sh, then these 12 files are minified, and then they’re deleted as pointless because the source files are shipped, along with the concatenation spec.

> updates the version number in `readme.txt`, etc.

Beside the stable tag in readme.txt, there are two instances of the version number to be maintained in footnotes.php.

> 2. take the resulting files and copy them to the SVN `trunk`, overwriting whatever's there

I don’t have enough experience to assess this process. I used to add or remove files one by one to/from version control in the SVN client, and commit. In the commit message, even double quotes enclosed in single quotes seem to need to be escaped, or SVN would fail to process a `\n` escape sequence.

> 3. create a new `tag` on the SVN repo. from `trunk` with the new version number (`svn cp trunk tags/<version number>`)

That is correct, too.

> Does that sound about right?

With the abovementioned caveats, yes, sounds good to me. Your automation effort is surely much appreciated, although I wouldn’t ask for so much.

Then there is also the pre-commit hook that you added support for.

**Comment by Rumperuu** [comment]
### Learning Points from this PR

This took much longer than intended and broke my own suggestions in `CONTRIBUTING.md` about keeping changes small and atomic. Part of that was unavoidable due to the scope of the changes, but there are alternative ways that would have worked better and avoided blocking development for so long. For future reference, a better way of introducing this change would have been to

a) implement the automated code validation
b) performed the automatic fixes
c) suppressed all other warnings
d) merge that

This would have ensured that we got ~80% of the way to a standardised codebase in a single sweep, whilst allowing the more difficult manual changes to be dealt with one-by-one in separate, less-monolithic and easier-to-review PRs. Something will certainly bear in mind in future workflow implementation (+ other projects).

> > > If Footnotes’ GitHub main branch is now having other line ends than its SVN repo, should this be updated WRT line ends so that the issue won’t be replicated there?
> > 
> > 
> > I've not touched the SVN repo. since I cloned it to here, so the SVN codebase will have never received [8d0ebdb](https://github.com/markcheret/footnotes/commit/8d0ebdb8595ab698c50996bc268bcabae928294d).
> 
> If we can be sure that SVN is EOL agnostic, it may not need it. But given GitHub is not, I doubt SVN is.
> 
> You are welcome to commit the EOL normalization and the standardised codebase. Hopefully SVN will then display a proper changeset, which I doubt it would without prior EOL normalisation.

Done!

**Pull request merged**
