### PR TITLE
ci: release process tweaks

### PR DESCRIPTION
**Pull request by Rumperuu**
This PR includes some tweaks arising from attempting to automate (mostly) the [2.7.1 release](https://github.com/markcheret/footnotes/discussions/104#discussioncomment-630871).

### CODE REVIEW

**Review by lolzim — APPROVED** [review]
🆗

**Review by markcheret — APPROVED** [review]
Looking neat. Thanks for the continuous debugging :)

**Comment by Rumperuu** [comment]
[BOOSH](https://github.com/markcheret/footnotes/actions/runs/765216325)

**Comment by markcheret** [comment]
looking good.
Only if I try to install it on a website with 2.7.0 it wants to add a second instance of footnotes?

**Comment by Rumperuu** [comment]
> looking good.
> Only if I try to install it on a website with 2.7.0 it wants to add a second instance of footnotes?

That seems like a WordPress quirk rather than anything to do with us, but I could be wrong

**Comment by markcheret** [comment]
@Rumperuu I see it now. The GH generated .zip unpacks in the wp-content/dist folder instead of /wp-content/footnotes

**Comment by markcheret** [comment]
the dist folder needs to be renamed to footnotes before zipping I guess.

**Comment by Rumperuu** [comment]
> the dist folder needs to be renamed to footnotes before zipping I guess.

Fixed in #131

**Pull request merged**
