### PR TITLE
fix: fix bug that caused footnotes to not be processed

### PR DESCRIPTION
**Pull request by Rumperuu**
Add the fix that @pewgeuges suggested via email

See https://wordpress.org/support/topic/problem-since-footnotes-2-5-14/

### CODE REVIEW

**Comment by lolzim** [comment]
I commited it yesterday in a branch 'pre-266' and see nothing of it now. What did I made wrong?

cu

**Review by lolzim — APPROVED** [review]
roll on

**Comment by Rumperuu** [comment]
> I commited it yesterday in a branch 'pre-266' and see nothing of it now. What did I made wrong?
> 
> cu

Did you `push` the branch? I can't see anything on [this repo.](https://github.com/markcheret/footnotes/branches/all) or the [SVN repo.](https://plugins.svn.wordpress.org/footnotes/branches/)

**Comment by lolzim** [comment]
> > I commited it yesterday in a branch 'pre-266' and see nothing of it now. What did I made wrong?
> > cu
> 
> Did you definitely `push` the branch? I can't see anything on [this repo.](https://github.com/markcheret/footnotes/branches/all) or the [SVN repo.](https://plugins.svn.wordpress.org/footnotes/branches/)

Maybe not. It wasn't on SVN anyway :)

**Pull request merged**
