### PR TITLE
fix: add separate prod/dev cache-busters

### LINKED ISSUE #80: Use file-modified timestamps for stylesheet cache busting
[`wp_register_style()`](https://developer.wordpress.org/reference/functions/wp_register_style/) can take an optional fourth argument that will override the use of the current WordPress version number as a URL query param appended to each CSS stylesheet , so that browsers will be forced to download new stylesheets rather that using cached old versions.

You can use whatever you want as the fourth argument. Currently (i.e., on the SVN repo.) a constant string named `C_STR_PACKAGE_VERSION` is used, representing the current package (development) version number.

A superior approach is to use `filemtime()` to get the last-modified time of each stylesheet file. This means that, even if a file is modified multiple times during a single version, the cache-busting will still work. This also means we do not have to manually update the string constant, and there is no chance of anyone forgetting to do so.

This change has already been made to the GitHub repo. in https://github.com/markcheret/footnotes/commit/a66faae03d720ea4dadf84b4f1bcf548e9c92502#commitcomment-49511226 — it has not yet been propagated to the SVN repo.

As far as I can tell, there is no compelling reason to prefer the use of the manually-updated package version string constant. If anyone disagrees, please explain why below.

### PR DESCRIPTION
**Pull request by Rumperuu**
Close #80

### CODE REVIEW

**Comment by pewgeuges** [comment]
I don’t get around this, and this is not top priority. 

I’ve renamed C_STR_PACKAGE_VERSION to C_STR_FOOTNOTES_VERSION and specified to use Version instead, as needed for production.

I strongly encourage you to focus your energy on debugging the plugin see #81

**Comment by markcheret** [comment]
> I’ve renamed C_STR_PACKAGE_VERSION to C_STR_FOOTNOTES_VERSION and specified to use Version instead, as needed for production.

I don't see your commit

**Comment by Rumperuu** [comment]
> I don’t get around this, and this is not top priority.
> 
> I’ve renamed C_STR_PACKAGE_VERSION to C_STR_FOOTNOTES_VERSION and specified to use Version instead, as needed for production.
> 
> I strongly encourage you to focus your energy on debugging the plugin see #81

@pewgeuges This is unhelpful. Renaming the constant does not address the fact that using the version number for cache busting _does not reliably bust the cache_ in a development context. That is, it does not do the _one_ thing that it is supposed to do—whilst it is not worse than useless, it _is_, effectively, useless. 

If you do not have any constructive objections to this PR, then just say so. If you would like to address #81, then make a branch and commit some code; please do not start trying to prioritise on my behalf.

**Review by markcheret — APPROVED** [review]
Thank you for this. That means we can test both mechanisms.

**Pull request merged**
