### PR TITLE
Move docs out of development/, and csscat.sh to css/

### PR DESCRIPTION
**Pull request by pewgeuges**
First of all, apologies for not requesting approval when adding these files.

Having them in `development/` is bad, so the two docs are moved to root, and `csscat.sh` goes where it belongs to, `css/`.

The two docs seem sort of useful, and the CSS handling script is needed when customizing stylesheets.

Can these be shipped with the Plugin, please?

### CODE REVIEW

**Comment by Rumperuu** [comment]
@pewgeuges Across 5894da5, a6e47b3 and 2bd9079 I've tidied up the CSS minification script and left some space to expand with automated minification later. I've also moved it into `_tools/` rather than `css/` for consistency, and renamed it to `build.sh` (with the intention of merging it into the `build.sh` from #59.

**Comment by pewgeuges** [comment]
> @pewgeuges Across [5894da5](https://github.com/markcheret/footnotes/commit/5894da52ab35344d8159b48fe66e2ff94dcf8fe5), [a6e47b3](https://github.com/markcheret/footnotes/commit/a6e47b3fdf4739eb38b777b17c16ce8fd0e2ff2e) and [2bd9079](https://github.com/markcheret/footnotes/commit/2bd9079512824fa6be26c722a589bed89004b3cd) I've tidied up the CSS minification script and left some space to expand with automated minification later (I'm assuming you're either manually minifying the files with an online tool or using some sort of VSCode plugin?) I've also moved it into `_tools/` rather than `css/` for consistency, and renamed it to `build.sh` with the intention of merging it with the `build.sh` from #59.
> 
> Correction: this will have to be kept separate from the automated build process until automated minification is implemented.

Thank you for refactoring the CSS build script. Indeed for minification I used a VSCode plugin.

Using `\n` in echo output requires the `-e` option.

**Comment by Rumperuu** [comment]
> > @pewgeuges Across [5894da5](https://github.com/markcheret/footnotes/commit/5894da52ab35344d8159b48fe66e2ff94dcf8fe5), [a6e47b3](https://github.com/markcheret/footnotes/commit/a6e47b3fdf4739eb38b777b17c16ce8fd0e2ff2e) and [2bd9079](https://github.com/markcheret/footnotes/commit/2bd9079512824fa6be26c722a589bed89004b3cd) I've tidied up the CSS minification script and left some space to expand with automated minification later (I'm assuming you're either manually minifying the files with an online tool or using some sort of VSCode plugin?) I've also moved it into `_tools/` rather than `css/` for consistency, and renamed it to `build.sh` with the intention of merging it with the `build.sh` from #59.
> > Correction: this will have to be kept separate from the automated build process until automated minification is implemented.
> 
> Thank you for refactoring the CSS build script. Indeed for minification I used a VSCode plugin.

Cool, I'll have to have a look to see if there's any Vim plugins for the time being, but ultimately the goal is to automate the minification so that we can run it in the GitHub Action triggered when we make a new release.

**Review by Rumperuu — APPROVED** [review]

**Comment by Rumperuu** [comment]
Merged with `release-workflow` in 3c40c63, closing this PR

**Pull request closed without merging**
