### PR TITLE
ci: rename folder during release process

### PR DESCRIPTION
**Pull request by Rumperuu**
Does what it says on the tin

### CODE REVIEW

**Review by lolzim — APPROVED** [review]
Yuk

**Review by markcheret — APPROVED** [review]
sweet. Thank you! I would've had to go on a hunt on the interwebs to figure out how to do this :)

**Comment by Rumperuu** [comment]
> sweet. Thank you! I would've had to go on a hunt on the interwebs to figure out how to do this :)

I gotta say, all of this automation work has been a great opportunity to pick up some fancy bash-fu

**Comment by markcheret** [comment]
Oh yeah!
I just recently had some fun switching my server backups over to a Git-Ops principle where the single source of truth of the target state is defined in a git repo and executed accordingly. So that was my latest bash journey :)

**Pull request merged**
