### PR TITLE
doc: update author url

### PR DESCRIPTION
**Pull request by markcheret**
All my tech-nerdy stuff found a new home. So I'm changing domain once again. I'll rework cheret.org soon for my artistic and private endeavours...

### CODE REVIEW

**Comment by Rumperuu** [comment]
Is your email address staying `.de`? There are mentions in `CODE_OF_CONDUCT.md`, `README.md`, `SECURITY.md`, `src/footnotes.php` and `src/js/wysiwyg-editor.js`.

**Comment by markcheret** [comment]
> Is your email address staying `.de`? There are mentions in `CODE_OF_CONDUCT.md`, `README.md`, `SECURITY.md`, `src/footnotes.php` and `src/js/wysiwyg-editor.js`.

Yes. That is still my main address.

**Review by Rumperuu — APPROVED** [review]

**Review by markcheret — COMMENTED** [review]
Double checked :)

**Review by lolzim — APPROVED** [review]
I am @lolzim and I approve this message

**Pull request merged**
