### PR TITLE
refactor: relocate Plugin settings

### PR DESCRIPTION
**Pull request by Rumperuu**
Moves the Plugin settings to the general options menu, and drops the ManFisher branding and diagnostics page.

See #34

### CODE REVIEW

**Comment by markcheret** [comment]
I think the diagnostics page is quite useful... Can it stay as a tab?
Why would you ditch it?

**Comment by Rumperuu** [comment]
> I think the diagnostics page is quite useful... Can it stay as a tab?
> Why would you ditch it?

The information is already provided by WordPress. Installed Plugins can be viewed in the Plugins tab, and the server name/PHP version/etc. in the Tools > Site Health tab.

**Comment by markcheret** [comment]
> > I think the diagnostics page is quite useful... Can it stay as a tab?
> > Why would you ditch it?
> 
> The information is already provided by WordPress. Installed Plugins can be viewed in the Plugins tab, and the server name/PHP version/etc. in the Tools > Site Health tab.

OK. Fair enough. Let's cut redundancies then.

**Review by markcheret — APPROVED** [review]
sweet!

**Pull request merged**
