### PR TITLE
Fix paragraph separation

### LINKED ISSUE #103: Premature end of note on paragraph separation
If a note contains a paragraph separator (As DIV or P), WP splits into blocks and the note ends on paragraph end. The rest of the text became part of the article.

1. Create a note 
2. Push 2x [Return] while editing it
2b. Alternatively, paste text containing CR/LF

The whole note text should be in the note

Editing like this
image

will shows like that
image

and that:
image

See: https://footnotes.lzi.ch/index.php/2021/02/08/test-1-5/

 - OS: macOS Big Sur
 - Browser: Up to date Firefox
 - Version: 2.7.0

### PR DESCRIPTION
**Pull request by markcheret**
Close #103

### CODE REVIEW

**Comment by markcheret** [comment]
which one to merge first? This or #114?

**Comment by Rumperuu** [comment]
> which one to merge first? This or #114?

#114 won't be done for a little while (see #116), so this one first

**Comment by markcheret** [comment]
> > which one to merge first? This or #114?
> 
> #114 won't be done for a little while (see #116), so this one first

OK. Thanks.

In this case, please review this PR and add missing docblocks info I might have missed 👍

**Review by markcheret — COMMENTED** [review]
Ready for review @lolzim and @Rumperuu

**Review by lolzim — APPROVED** [review]
one thing more, one thing less.

**Pull request merged**
