### PR TITLE
fixed insecure protocol warnings

### PR DESCRIPTION
**Pull request by markcheret**

### CODE REVIEW

**Comment by lolzim** [comment]
Question could be: should we have a Flash link, either in http or https ?!

**Comment by Rumperuu** [comment]
> Question could be: should we have a Flash link, either in http or https ?!

Hahaha, my thoughts exactly!

**Comment by markcheret** [comment]
There is some decluttering to do for sure

**Comment by Rumperuu** [comment]
> There is some decluttering to do for sure

For sure — jQuery Tools 1.2.7 came out in [_2012_](https://jquerytools.org/release-notes/version-1.2.x.html) and targets jQuery 1.7.1 (jQuery is currently on 3.6.0)!

**Review by Rumperuu — COMMENTED** [review]
Per @lolzim and my comments, I think we should leave this as it is (close the PR without merging) and instead focus on refactoring out the jQuery Tools dependency entirely as a priority task.

**Comment by lolzim** [comment]
OK for me. Mark talked about github tools for dev management, maybe it's time to test 'em. Tasks split then distribution could be a way.

**Comment by markcheret** [comment]
closing, as #85 will fix this in-depth of just a quick fix.

**Pull request closed without merging**
