### PR TITLE
build: add automated JS/CSS linting

### LINKED ISSUE #29: Add JS, CSS linting
Extended by #97

### PR DESCRIPTION
**Pull request by Rumperuu**
Close #29 
Fixing of Stylelint errors moved to #97

### CODE REVIEW

**Comment by markcheret** [comment]
Are all of these errors popping up "warnings" and "errors" in linting the code? Can we adjust the settings so that deprecation warnings cause the build to fail and some of the other checks pass with a "warning" grade?
Or d I take it correctly that there's a bunch of homework waiting for us?

**Comment by Rumperuu** [comment]
> Are all of these errors popping up "warnings" and "errors" in linting the code? Can we adjust the settings so that deprecation warnings cause the build to fail and some of the other checks pass with a "warning" grade?
> Or d I take it correctly that there's a bunch of homework waiting for us?

The JS and PHP pass without any warnings or errors. The CSS linter throws a load of errors (see attached pic), but they're the same three or four repeated over and over again so it shouldn't be too tricky to make it happy; just a bit mind-numbing.

Screenshot from 2021-04-15 05-00-48

**Comment by markcheret** [comment]
> The JS and PHP pass without any warnings or errors. The CSS linter throws a load of errors (see attached pic), but they're the same three or four repeated over and over again so it shouldn't be too tricky to make it happy; just a bit mind-numbing. But it'll only need doing once.

Hm. Does it make sense to split PHP, JS and CSS linting into separate checks?

**Comment by Rumperuu** [comment]
> > The JS and PHP pass without any warnings or errors. The CSS linter throws a load of errors (see attached pic), but they're the same three or four repeated over and over again so it shouldn't be too tricky to make it happy; just a bit mind-numbing. But it'll only need doing once.
> 
> Hm. Does it make sense to split PHP, JS and CSS linting into separate checks?

Yeah that sounds like a good idea, done in 7152579

**Review by markcheret — APPROVED** [review]
Hurray for linting!

**Pull request merged**
